[project]
name = "OnlineVideoDepthAnything"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python",
    "matplotlib",
    "imageio",
    "imageio-ffmpeg",
    "xformers",
    "einops",
    "natsort",
    "tifffile",
    "easydict",
    "tqdm",
    "jupyter",
    "onnx",
    "onnxruntime",
    "custom_utils",
]

[tool.setuptools.packages.find]
where = ["."] # Finds 'OnlineVideoDepthAnything' in the current directory

[tool.uv.sources]
custom_utils = { workspace = true }