net:
  encoder: vits
  features: 64
  out_channels:
  - 48
  - 96
  - 192
  - 384
  use_bn: false
  use_clstoken: false
  cache_size: 8
  pe: ape
  cross_att: true
  freeze_backbone: true
  use_xformers: False

pretrained_path: './checkpoints/oVDA_c8.pth'